server:
  port: 8082

#### MQTT配置
## username: EMQX的登录用户名
## password: EMQX的登录密码
## host-url: MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
## client-id: MQTT-连接服务器默认客户端ID
## default-topic: MQTT-默认的消息推送主题，实际可在调用接口时指定
## connection-timeout: 连接超时时间
## subscription-topic: 客户端订阅的主题，以下配置的是共享订阅 https://www.emqx.io/docs/zh/v5.0/mqtt/mqtt-shared-subscription.html#%E5%B8%A6%E7%BE%A4%E7%BB%84%E7%9A%84%E5%85%B1%E4%BA%AB%E8%AE%A2%E9%98%85
mqtt:
  username: admin
  password: public
  host-url:
    - tcp://localhost:1883
  client-id: mqttId2
  default-topic: topicA
  connection-timeout: 3000
  subscription-topic:
    - topicA
    - $share/group1/hello
    - $share/group1/hello1